/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rukh3D (https://sketchfab.com/rukh3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-bird-eagle-a12a4a928c324ffb8af5724e21eadf0a
Title: Robot Bird Eagle
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import scene from '../assets/3d/robot.glb'


//  3D Model from: https://sketchfab.com/3d-models/robot-bird-eagle-a12a4a928c324ffb8af5724e21eadf0a
const Robot = ({ currentAnimation, ...props }) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());

    if (actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
  }, [actions, currentAnimation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -0.5]} scale={0.1}>
          <group name="eaglefbx" rotation={[Math.PI / 2, 0, 0]} scale={0.02}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="amature" rotation={[-Math.PI / 2, 0, 0]} scale={60}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_84"
                      geometry={nodes.Object_84.geometry}
                      material={materials.Material}
                      skeleton={nodes.Object_84.skeleton}
                    />
                    <group name="Object_83" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  </group>
                </group>
                <group name="Eagle007" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Robot
